Added New German Formats and Adjusted French Format
EdgeTier/email-reply-parser pull request #23
Opened 2024-07-22 14:32 UTC by RachHMData

Added new formats for German.

In`QUOTE_HDR_REGEX`:
-format for parsing German. End of customer message: *'Ende der Kundennachricht'*

In `_MULTI_QUOTE_HDR_REGEX`:
- format for parsing German. *"Am 21.06.2024 um 09:49 schrieb X"*
- format for parsing German. *"X chrieb am Do. 20. Juni 2024 um 14:49:"*
- format for parsing German. Original message: *"-------- Ursprüngliche Nachricht --------"*
- format for parsing English/German. Forwarded message: *"-------- Forwarded message --------"*

In `EMAIL_SIGNOFF_REGEX`:
- format for parsing German. *'Mit freundlichen Grüßen'*
- format for parsing German. *'Freundliche Grüße'*

Also adjusted for cases when a colon isn't used for the french format in `_MULTI_QUOTE_HDR_REGEX`.

2024-08-08 12:54 UTC, paulminogue requested changes
Hey Rachel,

Really well done here! I just have two comments below. The second one is minor but the first may require some investigation!

Let me know if you need any help!

Example:
In [this BBG email](https://watchtower.edgetier.com/interaction/cb8a4cd5-ccb6-4f96-b32a-49b4ef7642cb) it seemed to cut things off mid-body when the customer said (translated) "your general conditions.".  From inspection it looks to me like the ":" character on the following line is making the parser think that the next line is a thread header so we maybe have to investigate things there


Separate to this it would maybe be also nice to write a test for this bit of regex `r"|(-{,10})(\s*)?(Ursprüngliche|Original|Forwarded).?(Nachricht|Message)(\s*)?(-{,10})" #German/English` as it is a bit scary!

2024-08-20 16:02 UTC, RachHMData commented
> Separate to this it would maybe be also nice to write a test for this bit of regex r"|(-{,10})(\s*)?(Ursprüngliche|Original|Forwarded).?(Nachricht|Message)(\s*)?(-{,10})" #German/English as it is a bit scary!

I ended up updating the regex here for this after some testing: 
`r"|-(-*)?\s?(Ursprüngliche|Original|Forwarded).?(Nachricht|Message)\s?(-*)?-"`
It was capturing just **"Forwarded Message"** on it's own so the regex should more accurately just capture if it's **--- Forwarded Message ---**.

I did write a test for this format previously: `test_orginal_message_sign_off`. I added a few more examples emails to the test, for each format variation.

2024-08-23 10:50 UTC, RachHMData commented
Updated the word limit default value to 1000 for the `cut_off_at_signature` function as during testing larger texts were not being parsed correctly due to the previously set word limit.

2024-08-27 08:52 UTC, paulminogue approved these changes
Well done!!!

2024-08-28 12:56 UTC, merged