Portuguese regex update
EdgeTier/email-reply-parser pull request #3
Opened 2022-12-15 10:45 UTC by katekiernan

2022-12-15 13:40 UTC, paulminogue commented on test/test_email_reply_parser.py
> +
Just out of curiosity, why does the parser merge this all onto one line?

2022-12-15 15:48 UTC, katekiernan commented on test/test_email_reply_parser.py
> +
I'm not 100%. It seems to be something to do with having the include signature parameter set to True when there's no signature detected. I made a slight change to the test, but I may need to look into that and see if I can figure out why it happens.

2022-12-15 18:09 UTC, paulminogue requested changes

2022-12-15 18:09 UTC, paulminogue commented on test/test_email_reply_parser.py
> +
OK so the issue starts in the `def keep_signoff(` function where if no signoff is found we trim to the word limit (see `def word_limit_cut_off(`). 

I think to fix this you just need to modify that function to:
```python
@staticmethod
  def word_limit_cut_off(body, word_limit):
      """
      Cut-off email at word limit.
      """
      if word_limit is not None:
          # if we can't find the sign-off, let's just take the first 100 words
          email_body_list = body.replace("\n", " \n").split(" ")
          newlines_offset = len([word for word in email_body_list if word == " \n"])
          body = " ".join(email_body_list[:word_limit + newlines_offset]).replace(" \n", "\n")

      return body
```
Without a default the split function will look for any white space including a newline so we will just specify the " " literally then handle any cases where we have just a plain newline by adding an offset onto the end.

I'd say you'll have to check the various tests on the watcher then once we merge this

2022-12-16 11:07 UTC, paulminogue approved these changes
Great work!

2022-12-16 11:11 UTC, merged